name: Hello World Workflow

# When this workflow runs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs to run
jobs:
  hello-world:
    # The type of runner
    runs-on: ubuntu-latest
    
    # Steps to execute
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Run a simple command
    - name: Say Hello
      run: echo "Hello, World! This is my first GitHub Action!"
      
    # Show current date and time
    - name: Show date
      run: date
      
    # List files in the repository
    - name: List files
      run: ls -la
      
    # Run multiple commands
    - name: System info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "GitHub Actor: ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"