name: File Analysis Workflow

# When this workflow runs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Jobs to run
jobs:
  analyze-files:
    # The type of runner
    runs-on: ubuntu-latest
    
    # Steps to execute
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    # Make the script executable
    - name: Make script executable
      run: chmod +x .github/scripts/analyze_files.py
        
    # Run the file analysis script
    - name: Analyze files for print statements
      run: python .github/scripts/analyze_files.py
      
    # Show repository structure
    - name: Show repository structure
      run: |
        echo "📁 Repository Structure:"
        echo "======================="
        find . -type f -not -path "./.git/*" | head -20
        
    # Show workflow info
    - name: Workflow Summary
      run: |
        echo "🚀 Workflow completed successfully!"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Event: ${{ github.event_name }}"